In [1]:
%matplotlib widget
import numpy as np
import matplotlib.pyplot as plt
import time
np.set_printoptions(suppress=True, precision=2)

In [2]:
def getRotm(angle):
    return np.array([[np.cos(angle), -np.sin(angle)], 
                     [np.sin(angle), np.cos(angle)]])                    

In [3]:
# euler angles 
angle = 90 * np.pi / 180    

# rotation matrix
rotm = getRotm(angle)
print(rotm)

# vector 
v = np.array([1, 0])
print(v)
v2 = rotm@v
print(v2)


[[ 0. -1.]
 [ 1.  0.]]
[1 0]
[0. 1.]


In [4]:
# inverse rotation = transpose
print("inverse rotation")   
print(np.linalg.inv(rotm))
print("transpose")
print(rotm.T)

# inverse vs transpose
def measure_tic_toc(foo):    
    tic = time.time()
    foo(rotm)
    toc = time.time()
    return toc - tic

""" Code below """
elapse1 = measure_tic_toc(np.linalg.inv)
elapse2 = measure_tic_toc(np.transpose)

""" End of cell """
print(f"inverse took {elapse1*1000} milli seconds")
print(f"transpose took {elapse2*1000} milli seconds")

inverse rotation
[[ 0.  1.]
 [-1.  0.]]
transpose
[[ 0.  1.]
 [-1.  0.]]
inverse took 0.03528594970703125 milli seconds
transpose took 0.005245208740234375 milli seconds


# 3D Rotation Matrix

In [5]:
def getRotm3D(euler):
    x, y, z = euler
    Rz = np.array([[np.cos(z), -np.sin(z), 0], 
                   [np.sin(z), np.cos(z), 0], 
                   [0, 0, 1]])
    Ry = np.array([[np.cos(y), 0, np.sin(y)], 
                   [0, 1, 0], 
                   [-np.sin(y), 0, np.cos(y)]])
    Rx = np.array([[1, 0, 0], 
                   [0, np.cos(x), -np.sin(x)],
                     [0, np.sin(x), np.cos(x)]])
    return Rz @ Ry @ Rx

In [6]:
#  euler angles
euler = np.array([45, 0, 0]) * np.pi / 180

# rotation matrix
rotm = getRotm3D(euler)
print(rotm)

# vector
v = np.array([1, 0, 0])
print(v)
v2 = rotm @ v
print(v2)



[[ 1.    0.    0.  ]
 [ 0.    0.71 -0.71]
 [ 0.    0.71  0.71]]
[1 0 0]
[1. 0. 0.]


In [7]:
euler = np.array([10, -5, 11]) * np.pi / 180

rotm = getRotm3D(euler)

roll = np.arctan2(rotm[2, 1], rotm[2, 2]) * 180 / np.pi
pitch = np.arctan2(-rotm[2, 0], np.sqrt(rotm[2, 1]**2 + rotm[2, 2]**2)) * 180 / np.pi
yaw = np.arctan2(rotm[1, 0], rotm[0, 0]) * 180 / np.pi

print(f"roll: {roll}, pitch: {pitch}, yaw: {yaw}")

roll: 10.0, pitch: -5.0, yaw: 10.999999999999998


In [8]:
rotm1 = getRotm3D(np.array([np.pi/2, 0, 0]))
rotm2 = getRotm3D(np.array([0, 0, np.pi/2]))

vf2 = rotm1 @ rotm2 @ np.array([1, 0, 0])
print(vf2)

[0. 0. 1.]
