In [1]:
import numpy as np
from imu.RotationUtils import RotationUtils

In [3]:
euler = np.array([1, 2, 3])*np.pi/180 + np.random.rand(3)*10**-1
rotm = RotationUtils.eul2rotm(euler)
print(rotm)

def orthonormalization(R):
    error = np.dot(R[:,0], R[:,1])
    # orthogonalization
    R0 = R[:,0] - error/2*R[:,1]
    R1 = R[:,1] - error/2*R[:,0]
    R2 = np.cross(R0, R1)
    # renormalization
    R[:,0] = 0.5*(3 - np.dot(R0, R0))*R0
    R[:,1] = 0.5*(3 - np.dot(R1, R1))*R1
    R[:,2] = 0.5*(3 - np.dot(R2, R2))*R2
    return R

ortho_rotm = orthonormalization(rotm) 
print(ortho_rotm)

[[ 0.99209525 -0.08939458  0.08806603]
 [ 0.09739729  0.99105757 -0.09120668]
 [-0.07912512  0.09906311  0.9919303 ]]
[[ 0.99209525 -0.08939458  0.08806603]
 [ 0.09739729  0.99105757 -0.09120668]
 [-0.07912512  0.09906311  0.9919303 ]]
