In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from imu.SO3 import SO3
from imu.SensorUtils import SensorUtils
from imu.RotationUtils import RotationUtils
np.set_printoptions(suppress=True, precision=2)

In [2]:
data = pd.read_csv('data/imu_x.csv')

euler_gt = data[['euler_x', 'euler_y', 'euler_z']].values
acc = data[['accelerometer_x', 'accelerometer_y', 'accelerometer_z']].values
mag = data[['magnetometer_x', 'magnetometer_y', 'magnetometer_z']].values

In [3]:
acc_si = SensorUtils.cvt_acc_si(acc)
N = acc_si.shape[0]


for i in range(N):
    euler = euler_gt[i] * np.pi / 180 + np.random.randn(3) * 0.01
    R_b2g = RotationUtils.eul2rotm(euler)
    acc_bdy = acc_si[i]
    #print(acc_bdy)
    acc_gnd = R_b2g @ acc_bdy
    print(acc_gnd)

    # error = acc_gnd - np.array([0, 0, -9.81])
    error_gnd = np.cross(acc_gnd, np.array([0, 0, -9.81]))
    error_bdy = R_b2g.T @ error_gnd
    dR = SO3.get_dR(error_bdy, 0.01)
    R_corr = R_b2g @ dR
    acc_gnd_corr = R_corr @ acc_bdy
    print(acc_gnd_corr)


[ 0.09  0.11 -9.81]
[ 0.    0.   -9.81]
[ 0.22 -0.04 -9.81]
[ 0.01 -0.   -9.81]
[ 0.14  0.01 -9.81]
[ 0.01  0.   -9.81]
[-0.1   0.08 -9.81]
[-0.    0.   -9.81]
[ 0.02 -0.05 -9.81]
[ 0.   -0.   -9.81]
[-0.06 -0.04 -9.81]
[-0.   -0.   -9.81]
[ 0.1   0.11 -9.81]
[ 0.    0.   -9.81]
[ 0.03 -0.02 -9.81]
[ 0.   -0.   -9.81]
[ 0.02  0.07 -9.81]
[ 0.    0.   -9.81]
[ 0.07 -0.24 -9.81]
[ 0.   -0.01 -9.81]
[-0.03  0.03 -9.81]
[-0.    0.   -9.81]
[ 0.03 -0.1  -9.81]
[ 0.   -0.   -9.81]
[-0.16 -0.04 -9.81]
[-0.01 -0.   -9.81]
[ 0.04  0.29 -9.81]
[ 0.    0.01 -9.81]
[-0.09 -0.01 -9.81]
[-0.   -0.   -9.81]
[-0.09 -0.05 -9.81]
[-0.   -0.   -9.81]
[-0.02 -0.15 -9.81]
[-0.   -0.01 -9.81]
[ 0.13  0.01 -9.81]
[ 0.    0.   -9.81]
[-0.07 -0.16 -9.81]
[-0.   -0.01 -9.81]
[ 0.01  0.18 -9.81]
[ 0.    0.01 -9.81]
[-0.08  0.18 -9.81]
[-0.    0.01 -9.81]
[-0.08 -0.13 -9.81]
[-0.   -0.   -9.81]
[ 0.07 -0.03 -9.81]
[ 0.   -0.   -9.81]
[ 0.05  0.12 -9.81]
[ 0.    0.   -9.81]
[-0.02 -0.04 -9.81]
[-0.   -0.   -9.81]


In [4]:
mag_si = SensorUtils.cvt_mag_si(mag)
N = acc.shape[0]

for i in range(N):
    eul = euler_gt[i] * np.pi / 180  # + np.random.randn(3) * 0.001
    R_b2g = RotationUtils.eul2rotm(eul)
    mag_bdy = mag_si[i]
    mag_gnd = R_b2g @ mag_bdy
    print(mag_gnd)

    # error = np.cross(acc_gnd, np.array([0, 0, -9.81]))
    # print("error", error)



[1. 0. 0.]
[1. 0. 0.]
[1. 0. 0.]
[1. 0. 0.]
[1. 0. 0.]
[1. 0. 0.]
[1. 0. 0.]
[1. 0. 0.]
[1. 0. 0.]
[1. 0. 0.]
[1. 0. 0.]
[1. 0. 0.]
[1. 0. 0.]
[1. 0. 0.]
[1. 0. 0.]
[1. 0. 0.]
[1. 0. 0.]
[1. 0. 0.]
[1. 0. 0.]
[1. 0. 0.]
[1. 0. 0.]
[1. 0. 0.]
[1. 0. 0.]
[1. 0. 0.]
[1. 0. 0.]
[1. 0. 0.]
[1. 0. 0.]
[1. 0. 0.]
[1. 0. 0.]
[1. 0. 0.]
[1. 0. 0.]
[1. 0. 0.]
[1. 0. 0.]
[1. 0. 0.]
[1. 0. 0.]
[1. 0. 0.]
[1. 0. 0.]
[1. 0. 0.]
[1. 0. 0.]
[1. 0. 0.]
[1. 0. 0.]
[1. 0. 0.]
[1. 0. 0.]
[1. 0. 0.]
[1. 0. 0.]
[1. 0. 0.]
[1. 0. 0.]
[1. 0. 0.]
[1. 0. 0.]
[1. 0. 0.]
[1. 0. 0.]
[1. 0. 0.]
[1. 0. 0.]
[1. 0. 0.]
[1. 0. 0.]
[1. 0. 0.]
[1. 0. 0.]
[1. 0. 0.]
[1. 0. 0.]
[1. 0. 0.]
[1. 0. 0.]
[1. 0. 0.]
[1. 0. 0.]
[1. 0. 0.]
[1. 0. 0.]
[1. 0. 0.]
[1. 0. 0.]
[1. 0. 0.]
[1. 0. 0.]
[1. 0. 0.]
[1. 0. 0.]
[1. 0. 0.]
[1. 0. 0.]
[1. 0. 0.]
[1. 0. 0.]
[1. 0. 0.]
[1. 0. 0.]
[1. 0. 0.]
[1. 0. 0.]
[1. 0. 0.]
[1. 0. 0.]
[1. 0. 0.]
[1. 0. 0.]
[1. 0. 0.]
[1. 0. 0.]
[1. 0. 0.]
[1. 0. 0.]
[1. 0. 0.]
[1. 0. 0.]
[1. 0. 0.]
[1. 0. 0.]